#!/bin/bash

set -euo pipefail

MSdescr="KalAO hardware execution script"

source milk-script-std-config

##### Prerequisites
RequiredCommands=( tmux milk )
RequiredFiles=()
RequiredDirs=()

##### parse arguments
source milk-argparse


DM_LOOPNAME="KalAO-dmloop"
#LOOP_WORKDIR=$(<${LOOP_CONFNAME}-conf/WORKDIR)
#LOOP_LOOPNAME=$(<${LOOP_CONFNAME}-conf/LOOPNAME)

TTM_LOOPNAME="KalAO-ttmloop"
#TTMLOOP_LOOPNAME=$(<${LOOP_CONFNAME}-conf/LOOPNAME)

# to be called rootdir
#LOOP_ROOTDIR=${LOOP_LOOPNAME}-rootdir
#LOOP_RUNDIR=${LOOP_LOOPNAME}-rundir

HARDWARE_LOOPNAME="kalaoHWloop"




function sendFPScmd {
  echo "SENDING: $1"
  echo "$1" >> ${MILK_SHM_DIR}/${HARDWARE_LOOPNAME}_fpsCTRL.fifo
}

function waitFile {
	echo -n "Waiting $1 "
	while [ ! -f $1 ] ;
	do
		echo -n "."
      	sleep 0.1
	done
	echo " Done"
	sleep 0.1
}

# ======================================================================
# Start all processes
# ======================================================================

stepFile="step.aolaunch.START"
if [ ! -f "$stepFile" ]; then

##### Launch processes dmloopsim

cacao-loop-deploy "${DM_LOOPNAME}"

#cacao-task-manager -X 4 "${LOOP_CONFNAME}"

cacao-loop-deploy "${TTM_LOOPNAME}"
#cacao-task-manager -X 4 "${TTMLOOP_CONFNAME}"

##### Launch processes hardware

source ${DM_LOOPNAME}-conf/cacaovars.bash

##### Load infos for dm


HARDWARE_ROOTDIR=${HARDWARE_LOOPNAME}-rootdir
HARDWARE_RUNDIR=${HARDWARE_LOOPNAME}-rundir

#source ${HARDWARE_CONFNAME}-conf/cacaovars.${HARDWARE_LOOPNAME}.bash

#DM_DMINDEX=$CACAO_DMINDEX

cacao-task-manager -X 4 "${HARDWARE_CONFNAME}"

cp -R hardware_setupfiles/* ${HARDWARE_ROOTDIR}/${HARDWARE_RUNDIR}

##### Launch processes ttm loop

#cacao-task-manager -X 4 "${TTM_CONFNAME}"

touch ${stepFile}

exit

else
echo "found ${stepFile} -> skipping"
fi

stepFile="step.aolaunch.HW"
if [ ! -f "$stepFile" ]; then

source ${DM_LOOPNAME}-conf/cacaovars.bash

##### Start hardware

# TODO use DMINDEX and LOOPNUMBER to define name
sendFPScmd "runstart DMch2disp-01"

sendFPScmd "runstart DMch2disp-02"

#sendFPScmd "confwupdate bmc_display"
sendFPScmd "runstart bmc_display"


#Temporary fix for the process name change
if [ ! -f /tmp/milk/shwfs_process.fps.shm ]; then
	ln -s /tmp/milk/shwfs_process-1.fps.shm /tmp/milk/shwfs_process.fps.shm
fi

#sendFPScmd "confwupdate nuvu_acquire"
sendFPScmd "runstart nuvu_acquire"


##### Load dm flat

waitFile "${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp00.im.shm"

pushd ${HARDWARE_ROOTDIR}/${HARDWARE_RUNDIR} #${HARDWARE_ROOTDIR}/hardware-setupfiles

cacao << EOF
loadfits "flat_dm.fits" dmflat
readshmim dm${CACAO_DMINDEX}disp00
cpsh dmflat dm${CACAO_DMINDEX}disp00
exitCLI
EOF

popd

touch ${stepFile}
exit

else
echo "found ${stepFile} -> skipping"
fi

# ======================================================================
# Start SHWFS
# ======================================================================

stepFile="step.aolaunch.SHWFS"
if [ ! -f "$stepFile" ]; then

waitFile "${MILK_SHM_DIR}/nuvu_stream.im.shm"

#sendFPScmd "confwupdate shwfs_process"
sendFPScmd "runstart shwfs_process"

touch ${stepFile}
exit
else
echo "found ${stepFile} -> skipping"
fi

# ======================================================================
# Close AO loop
# ======================================================================

stepFile="step.aolaunch.LOOPRUN"
if [ ! -f "$stepFile" ]; then

sendFPScmd "waitonrunOFF"

pushd ${HARDWARE_ROOTDIR}/${HARDWARE_RUNDIR}

cacao << EOF
loadfits "fps.compsCM-1.datadir/sCMat00.fits" sCMat00_1
cpsh sCMat00_1 aol1_CMat
exitCLI
EOF

popd
fi
#sendFPScmd "confwupdate loopRUN-${DM_LOOPNUMBER}"

